<?php
/**
 * @file
 * Code for the stanford help feature.
 */

include_once 'stanford_help.features.inc';


/**
 * Default settings wrapper for variable_get
 * @return [type] [description]
 */
function stanford_help_get_settings() {
  $default_settings = array(
    'site_specific_help_title' => t('See site specific help'),
    'site_specific_help_url' => 'site-help',
  );
  $settings = variable_get('stanford_help_settings', $default_settings );

  return $settings;
}


/**
 * Implements hook_block_info().
 */
function stanford_help_block_info() {
  $blocks = array();
  $blocks['stanford_site_specific_help'] = array(
    'info' => t('Stanford Site Specific Help'),
  );

  return $blocks;
}
/**
 * Implements hook_block_configure().
 */
function stanford_help_block_configure($delta='') {
  $form = array();

  switch($delta) {
    case 'stanford_site_specific_help' :
      $settings = stanford_help_get_settings();

      // Title
      $form['site_specific_help_title'] = array(
        '#type' => 'textfield',
        '#title' => t('Site Specific Help Button Title'),
        '#default_value' => $settings['site_specific_help_title'],
        '#required' => TRUE,
      );

      // URL
      $form['site_specific_help_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Site Specific Help Button URL'),
        '#default_value' => $settings['site_specific_help_url'],
        '#required' => TRUE,
      );

      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function stanford_help_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'stanford_site_specific_help' :

      $settings = stanford_help_get_settings();
      $new_settings = array_merge($settings, $edit);

      $new_settings['site_specific_help_title'] = filter_xss($new_settings['site_specific_help_title']);
      $new_settings['site_specific_help_url'] = filter_xss($new_settings['site_specific_help_url']);

      variable_set('stanford_help_settings', $new_settings);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function stanford_help_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'stanford_site_specific_help' :
      $block['content'] = stanford_site_specific_help_block_view();
      break;
  }

  return $block;
}

function stanford_site_specific_help_block_view()
{
  $block = array();
  $settings = stanford_help_get_settings();
  $block = array(
    'site_specific_help_link' => array(
      '#type' => 'markup',
      '#markup' => l($settings['site_specific_help_title'],
        $settings['site_specific_help_url'],
        array('attributes' => array('class' => 'btn btn-request'))),
    ),
  );
  return $block;
}

